### ISSUE TITLE
DataPower Failed to respond

### ISSUE THREAD

**Issue by dxniel7402** [Appdynamics/datapower-monitoring-extension#6]
Hi,

i have the problem here that i don't get any metrics. In the logs comes continuously the following error message:

```
Win10 ==> [Monitor-Task-Thread2] 12 Jan 2022 18:57:44,559 ERROR BulkApiMetricFetcher-DataPowerMonitor - Error while fetching the data from absolute url=[https://datapower.com:8888/service/mgmt/current] and payload=[<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body xmlns:dp="http://www.datapower.com/schemas/management"><dp:request domain="default"><dp:get-status class="MemoryStatus"/></dp:request><dp:request domain="default"><dp:get-status class="FilesystemStatus"/></dp:request><dp:request domain="default"><dp:get-status class="CPUUsage"/></dp:request><dp:request domain="default"><dp:get-status class="SystemUsage"/></dp:request><dp:request domain="default"><dp:get-status class="SystemUsage2Table"/></dp:request></SOAP-ENV:Body></SOAP-ENV:Envelope>]
org.apache.http.NoHttpResponseException: datapower.com:8888 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:4.5.13]
	at com.appdynamics.extensions.datapower.BulkApiMetricFetcher.getResponse(BulkApiMetricFetcher.java:114) [?:?]
	at com.appdynamics.extensions.datapower.BulkApiMetricFetcher.getResponse(BulkApiMetricFetcher.java:87) [?:?]
	at com.appdynamics.extensions.datapower.BulkApiMetricFetcher.getResponseForSystemWide(BulkApiMetricFetcher.java:82) [?:?]
	at com.appdynamics.extensions.datapower.BulkApiMetricFetcher.fetchMetrics(BulkApiMetricFetcher.java:60) [?:?]
	at com.appdynamics.extensions.datapower.MetricFetcher.run(MetricFetcher.java:68) [?:?]
	at com.appdynamics.extensions.executorservice.MonitorThreadPoolExecutor$TaskRunnable.run(MonitorThreadPoolExecutor.java:113) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
_URI was replaced_

If I send a curl from the same machine with the same credentials, I get a response:

```
curl -u user:password -d '<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><SOAP-ENV:Body xmlns:dp="http://www.datapower.com/schemas/management"><dp:request domain="default"><dp:get-status class="FirmwareVersion3"/></dp:request></SOAP-ENV:Body></SOAP-ENV:Envelope>' https://datapower.com:8888/service/mgmt/current
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1070    0   785  100   285   9437   3426 --:--:-- --:--:-- --:--:-- 13048<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Body><dp:response xmlns:dp="http://www.datapower.com/schemas/management"><dp:timestamp>2022-01-12T18:37:07+01:00</dp:timestamp><dp:status><FirmwareVersion3 xmlns:env="http://www.w3.org/2003/05/soap-envelope">
<Serial>7803169</Serial>
<Version>IDG.10.X.X.X</Version>
<Build>XXXXX</Build>
<BuildDate>XXXXX</BuildDate>
<DeliveryType>XXX</DeliveryType>
<WatchdogBuild>XXXX</WatchdogBuild>
<InstalledDPOS>XXXXX</InstalledDPOS>
<RunningDPOS>XXXXXX</RunningDPOS>
<XMLAccelerator>embedded</XMLAccelerator>
<MachineType>XXXXXX</MachineType>
<ModelType>XXXXXXXX</ModelType>
<Tenant/></FirmwareVersion3></dp:status></dp:response></env:Body></env:Envelope>

```

Unfortunately, I can't find a solution to this anywhere - The SOAP interface should be configured correctly in the DP, as we use CA Wily Introscope in parallel. Can anyone help us further?

**Comment by dxniel7402** [comment]
@satish-m @ugolee @BalakrishnaV @abeytom07
